const weather = {
    0: {text: 'Ciel dégagé', icon: 'sunny'},
    1: {text: 'Principalement dégagé', icon: 'sunny'},
    2: {text: 'Partiellement nuageux', icon: 'partly_cloudy_day'},
    3: {text: 'Couvert', icon: 'cloud'},
    45: {text: 'Brouillard', icon: 'foggy'},
    48: {text: 'Brouillard givrant', icon: 'foggy'},
    51: {text: 'Légère bruine', icon: 'mist'},
    53: {text: 'Bruine', icon: 'mist'},
    55: {text: 'Bruine dense', icon: 'mist'},
    56: {text: 'Légère bruine givrante', icon: 'mist'},
    57: {text: 'Buine givrante dense', icon: 'mist'},
    61: {text: 'Légère pluie', icon: 'rainy_light'},
    63: {text: 'Pluie', icon: 'rainy'},
    64: {text: 'Forte pluie', icon: 'rainy_heavy'},
    66: {text: 'Légère pluie verglaçante', icon: 'weather_mix'},
    67: {text: 'Forte pluie verglaçante', icon: 'weather_mix'},
    71: {text: 'Quelques flocons', icon: 'weather_snowy'},
    73: {text: 'Neige', icon: 'snowing'},
    75: {text: 'Grosses chutes de neige', icon: 'snowing_heavy'},
    77: {text: 'Grésil', icon: 'weather_mix'},
    80: {text: 'Légères averses', icon: 'rainy_light'},
    81: {text: 'Averses', icon: 'rainy'},
    82: {text: 'Fortes averses', icon: 'rainy_heavy'},
    85: {text: 'Petites averses de neige', icon: 'snowing'},
    86: {text: 'Fortes averses de neige', icon: 'snowing_heavy'},
    95: {text: 'Orages', icon: 'thunderstorm'},
    96: {text: 'Orages et grêle', icon: 'weather_hail'},
    99: {text: 'Orages et fortes chutes de grêle', icon: 'weather_hail'},
}